# Generated by Django 5.2.1 on 2025-06-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='Starting Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('location', models.CharField(max_length=200)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('image', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2)),
            ],
        ),
    ]
