# Generated by Django 5.2.1 on 2025-06-10 13:16

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight(g)')),
                ('category', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('drinks', 'Drinks')], max_length=20, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('big_three', 'Big Three (Backpack, Tent, Sleeping Bag)'), ('water', 'Water'), ('food', 'Food Storage'), ('cooking', 'Cooking & Utensils'), ('clothing', 'Clothing & Footwear'), ('toiletries', 'Toiletries'), ('tools', 'Tools'), ('saftey', 'Saftey'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment')], max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Item name')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('own', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_m', models.CharField(blank=True, choices=[('oz', 'oz'), ('lb', 'lb'), ('g', 'g'), ('kg', 'kg')], max_length=2, null=True, verbose_name='Weight Measurment')),
                ('packed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='Starting Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('location', models.CharField(max_length=200)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('image', models.CharField(choices=[('1', ''), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('gear', models.ManyToManyField(to='main_app.gear')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('start_location', models.CharField(max_length=200)),
                ('finish_location', models.CharField(max_length=200)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(max_length=250)),
                ('food', models.ManyToManyField(to='main_app.food')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trail')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
