# Generated by Django 5.2.1 on 2025-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_trail_image_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('big_three', 'Big Three (Backpack, Tent, Sleeping Bag)'), ('water', 'Water'), ('food', 'Food Storage'), ('cooking', 'Cooking & Utensils'), ('clothing', 'Clothing & Footwear'), ('toiletries', 'Toiletries'), ('tools', 'Tools'), ('saftey', 'Saftey'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment')], max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Item name')),
                ('brand', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('own', models.BooleanField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_m', models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('g', 'g'), ('kg', 'kg')], max_length=2, verbose_name='Weight Measurment')),
            ],
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
    ]
