# Generated by Django 5.2.1 on 2025-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gear_alter_day_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weight_m',
            field=models.CharField(blank=True, choices=[('oz', 'oz'), ('lb', 'lb'), ('g', 'g'), ('kg', 'kg')], max_length=2, null=True, verbose_name='Weight Measurment'),
        ),
    ]
