# Generated by Django 5.2.1 on 2025-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_gear_brand_alter_gear_link_alter_gear_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='own',
            field=models.BooleanField(default=False),
        ),
    ]
