# Generated by Django 5.2.1 on 2025-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_trail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, default='cover_image_1.jpg', null=True, upload_to='cover_image/'),
        ),
    ]
