# Generated by Django 5.2.1 on 2025-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_gear_own'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='trail',
            name='gear',
            field=models.ManyToManyField(to='main_app.gear'),
        ),
    ]
