# Generated by Django 5.2.1 on 2025-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_trail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='finish_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='finish_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='start_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
