# Generated by Django 5.2.1 on 2025-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_gear_options_trail_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
