# Generated by Django 5.2.1 on 2025-06-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_day_finish_lat_day_finish_long_day_start_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='finish_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='start_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
