# Generated by Django 5.2.1 on 2025-06-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_day_finish_location_alter_day_start_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='weight_lb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weight_m',
            field=models.CharField(blank=True, choices=[('oz', 'oz'), ('lb', 'lb')], max_length=2, null=True, verbose_name='Weight Measurment'),
        ),
    ]
