# Generated by Django 5.2.1 on 2025-06-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_gear_weight_lb_alter_gear_weight_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='weight_lb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
