# Generated by Django 5.2.1 on 2025-06-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_location_alter_gear_options_alter_meal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
