# Generated by Django 5.2.1 on 2025-06-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_gear_weight_lb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='weight_lb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
