# Generated by Django 5.2.1 on 2025-06-10 01:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_location_trail_lat_trail_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight(g)')),
                ('category', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('drinks', 'Drinks')], max_length=20, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.RemoveField(
            model_name='day',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='day',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
