# Generated by Django 5.2.1 on 2025-06-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_gear_weight_lb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
