# Generated by Django 5.2.1 on 2025-06-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_food_remove_day_meal_remove_mealplan_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='food',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
