# Generated by Django 5.2.1 on 2025-06-11 15:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='notes',
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=250)),
                ('created', models.DateField(default=datetime.datetime(2025, 6, 11, 15, 45, 35, 685052, tzinfo=datetime.timezone.utc))),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.day')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
