# Generated by Django 5.2.1 on 2025-06-11 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_note_delete_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 16, 6, 14, 782509, tzinfo=datetime.timezone.utc)),
        ),
    ]
