# Generated by Django 5.2.1 on 2025-06-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_note_options_trail_user_alter_note_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='user',
        ),
    ]
