# Generated by Django 5.2.1 on 2025-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_day_user_food_user_gear_user_note_user_trail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
