# Generated by Django 5.2.1 on 2025-06-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_trail_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
