# Generated by Django 5.2.1 on 2025-06-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_day_user_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance(mi)'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Elevation Gain(ft)'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
