# Generated by Django 5.2.1 on 2025-06-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_trail_distance_alter_trail_elevation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Starting Location'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Adventure Name'),
        ),
    ]
