# Generated by Django 5.2.1 on 2025-06-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_trail_location_alter_trail_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trail',
            options={'ordering': ['start_date']},
        ),
    ]
