# Generated by Django 5.2.1 on 2025-06-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_trail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='finish_campsite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finishing Campsite Name'),
        ),
        migrations.AddField(
            model_name='day',
            name='start_campsite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Starting Campsite Name'),
        ),
        migrations.AddField(
            model_name='trail',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Starting Location Name'),
        ),
        migrations.AlterField(
            model_name='day',
            name='finish_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Campsite Address'),
        ),
        migrations.AlterField(
            model_name='day',
            name='start_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Campsite Address'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='image',
            field=models.CharField(choices=[('cover_image_1.jpg', 'Image 1'), ('cover_image_2.jpg', 'Image 2'), ('cover_image_3.jpg', 'Image 3'), ('cover_image_4.jpg', 'Image 4'), ('cover_image_5.jpg', 'Image 5'), ('cover_image_6.jpg', 'Image 6'), ('cover_image_7.jpg', 'Image 7'), ('cover_image_8.jpg', 'Image 8'), ('cover_image_10.jpg', 'Image 10')], default='Image 7', max_length=100, verbose_name='Cover Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Starting Location Address'),
        ),
    ]
