# Generated by Django 5.2.1 on 2025-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_day_finish_campsite_day_start_campsite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(max_length=250),
        ),
    ]
