# Generated by Django 5.2.1 on 2025-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance (mi)'),
        ),
        migrations.AlterField(
            model_name='day',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Elevation Gain (ft)'),
        ),
        migrations.AlterField(
            model_name='day',
            name='finish_campsite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='day',
            name='finish_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='day',
            name='start_campsite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='day',
            name='start_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weight_lb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance (mi)'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Elevation Gain (ft)'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
