# Generated by Django 5.2.1 on 2025-06-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_day_distance_alter_day_elevation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight (g)'),
        ),
    ]
