# Generated by Django 5.2.1 on 2025-06-16 00:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_food_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Weight (g)'),
        ),
    ]
