# Generated by Django 5.2.1 on 2025-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_remove_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('Big Three', 'Big Three (Backpack, Tent, Sleeping Bag)'), ('Water', 'Water'), ('Food', 'Food Storage'), ('Cooking', 'Cooking & Utensils'), ('Clothing', 'Clothing & Footwear'), ('Toiletries', 'Toiletries'), ('Tools', 'Tools'), ('Saftey', 'Saftey'), ('Electronics', 'Electronics'), ('Entertainment', 'Entertainment')], max_length=20),
        ),
    ]
