# Generated by Django 5.2.1 on 2025-06-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_alter_gear_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('big_three', 'Big Three (Backpack, Tent, Sleeping Bag)'), ('water', 'Water'), ('food', 'Food Storage'), ('cooking', 'Cooking & Utensils'), ('clothing', 'Clothing & Footwear'), ('toiletries', 'Toiletries'), ('tools', 'Tools'), ('saftey', 'Saftey'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment')], max_length=20),
        ),
    ]
