# Generated by Django 5.2.3 on 2025-06-16 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_alter_gear_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name* '),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Weight (grams)'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('big_three', 'Big Three (Backpack, Tent, Sleeping Bag)'), ('water', 'Water'), ('food', 'Food Storage'), ('cooking', 'Cooking & Utensils'), ('clothing', 'Clothing & Footwear'), ('toiletries', 'Toiletries'), ('tools', 'Tools'), ('saftey', 'Saftey'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment')], max_length=20, verbose_name='Category* '),
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Item name* '),
        ),
        migrations.AlterField(
            model_name='trail',
            name='end_date',
            field=models.DateField(verbose_name='End Date* '),
        ),
        migrations.AlterField(
            model_name='trail',
            name='image',
            field=models.CharField(choices=[('cover_image_1.jpg', 'Image 1'), ('cover_image_2.jpg', 'Image 2'), ('cover_image_3.jpg', 'Image 3'), ('cover_image_4.jpg', 'Image 4'), ('cover_image_5.jpg', 'Image 5'), ('cover_image_6.jpg', 'Image 6'), ('cover_image_7.jpg', 'Image 7'), ('cover_image_8.jpg', 'Image 8'), ('cover_image_10.jpg', 'Image 10')], max_length=100, verbose_name='Cover Image* '),
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Adventure Name* '),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start_date',
            field=models.DateField(verbose_name='Start Date* '),
        ),
    ]
